class_id_to_name = {
    "1": "apple",
    "2": "ball",
    "3": "banana",
    "4": "bell_pepper",
    "5": "binder",
    "6": "bowl",
    "7": "calculator",
    "8": "camera",
    "9": "cap",
    "10": "cell_phone",
    "11": "cereal_box",
    "12": "coffee_mug",
    "13": "comb",
    "14": "dry_battery",
    "15": "flashlight",
    "16": "food_bag",
    "17": "food_box",
    "18": "food_can",
    "19": "food_cup",
    "20": "food_jar",
    "21": "garlic",
    "22": "glue_stick",
    "23": "greens",
    "24": "hand_towel",
    "25": "instant_noodles",
    "26": "keyboard",
    "27": "kleenex",
    "28": "lemon",
    "29": "lightbulb",
    "30": "lime",
    "31": "marker",
    "32": "mushroom",
    "33": "notebook",
    "34": "onion",
    "35": "orange",
    "36": "peach",
    "37": "pear",
    "38": "pitcher",
    "39": "plate",
    "40": "pliers",
    "41": "potato",
    "42": "rubber_eraser",
    "43": "scissors",
    "44": "shampoo",
    "45": "soda_can",
    "46": "sponge",
    "47": "stapler",
    "48": "tomato",
    "49": "toothbrush",
    "50": "toothpaste",
    "51": "water_bottle"
}
class_name_to_id = {v: k for k, v in class_id_to_name.items()}

class_names = set(class_id_to_name.values())

